### ISSUE TITLE
adapter不显示内容

### ISSUE THREAD

**Issue by lulu75** [jiarWang/RepeatLayoutManager#1]
项目运行起来页面没有内容，将项目中RepeatLayoutManager替换为LinearLayoutManager页面显示正常。

**Comment by jiarWang** [comment]
请提供一下你recyclerview的xml布局代码，所使用的版本号，以及使用manager的代码

不显示的

**Comment by jiarWang** [comment]
不显示的原因可能是recyclerview本身的高度为0

麻烦提供一下布局代码及版本号
